#!/bin/bash

echo "🧪 TEST DIRECTO DESDE VERCEL"
echo "============================"
echo ""

echo "✅ Backend confirmado funcionando: Status 200"
echo "✅ CORS confirmado funcionando: Origin permitido"
echo ""

echo "🔍 Ahora probemos desde tu frontend..."
echo ""
echo "📋 INSTRUCCIONES:"
echo "1. Abre tu app: https://toolitex-ah.vercel.app"
echo "2. Abre DevTools (F12) → Console"
echo "3. Ejecuta los siguientes comandos uno por uno:"
echo ""

echo "// 1. Verificar variable de entorno"
echo "console.log('API URL:', process.env.REACT_APP_API_URL);"
echo ""

echo "// 2. Test de conectividad básica"
echo "fetch('https://toolitexah-production.up.railway.app/')"
echo "  .then(r => r.text())"
echo "  .then(data => console.log('✅ Backend conectado:', data))"
echo "  .catch(err => console.error('❌ Error:', err));"
echo ""

echo "// 3. Test de registro completo"
echo "fetch('https://toolitexah-production.up.railway.app/api/auth/register', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    name: 'UsuarioPrueba',"
echo "    email: 'test' + Date.now() + '@test.com',"
echo "    password: 'TestPass123@'"
echo "  })"
echo "})"
echo ".then(r => {"
echo "  console.log('Status:', r.status);"
echo "  return r.json();"
echo "})"
echo ".then(data => console.log('✅ Registro exitoso:', data))"
echo ".catch(err => console.error('❌ Error de registro:', err));"
echo ""

echo "📝 RESULTADOS ESPERADOS:"
echo "1. API URL debe mostrar: https://toolitexah-production.up.railway.app"
echo "2. Backend conectado debe mostrar: 'API funcionando'"
echo "3. Registro exitoso debe mostrar el token y datos del usuario"
echo ""

echo "🚨 SI VES ERRORES:"
echo "- Network Error → Problema de conectividad"
echo "- CORS Error → Problema de origen"
echo "- 400 Bad Request → Datos inválidos"
echo "- 404 Not Found → URL incorrecta"
